version: '3.7'
services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
      network: host
    ports:
      - "5000:5000"
    volumes:
      - ../..:/app
    env_file: .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:15.2-alpine3.17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db
  redis:
    image: redis:7.0.0-alpine
    command: redis-server
    volumes:
      - /var/lib/redis/data
    ports:
      - "6379:6379"
volumes:
  postgres_data: