"""empty message

Revision ID: 320c7b3020f8
Revises: 3da3e732640f
Create Date: 2023-03-17 07:07:55.627122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320c7b3020f8'
down_revision = '3da3e732640f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('reg_plates', sa.String(length=15), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reg_plates')
    )
    op.add_column('employees', sa.Column('email', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'employees', ['email'])
    op.add_column('routes', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'routes', 'vehicles', ['vehicle_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.add_column('users', sa.Column('send_routes_to_employees', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_foreign_key('user_address_fk', 'users', 'addresses', ['depot_addr_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_address_fk', 'users', type_='foreignkey')
    op.drop_column('users', 'send_routes_to_employees')
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.drop_column('routes', 'vehicle_id')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_column('employees', 'email')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
