"""empty message

Revision ID: 69af95df5bf8
Revises: 8d2db133cae5
Create Date: 2023-05-15 15:31:54.018031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69af95df5bf8'
down_revision = '8d2db133cae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'link', existing_type=sa.String(length=1500), type_=sa.TEXT())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routes', 'link', existing_type=sa.TEXT(), type_=sa.String(length=1500))
    # ### end Alembic commands ###
