"""empty message

Revision ID: 98535ecf4791
Revises: 320c7b3020f8
Create Date: 2023-03-24 01:24:20.005593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98535ecf4791'
down_revision = '320c7b3020f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('version', sa.Integer(), server_default='0', nullable=False))
    op.add_column('vehicles', sa.Column('version', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'version')
    op.drop_column('employees', 'version')
    # ### end Alembic commands ###
